 name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r frontend/requirements.txt
        
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Build Backend
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        
    - name: Build Frontend
      run: |
        python build.py
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CovEngineV2
        path: dist/CovEngineV2/
        
    - name: Create ZIP Archive
      if: github.event_name == 'release'
      run: |
        cd dist
        7z a -tzip CovEngineV2.zip CovEngineV2/
        
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/CovEngineV2.zip
        asset_name: CovEngineV2.zip
        asset_content_type: application/zip
